AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Resume Analyzer - AWS SAM Template

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref ResumeAnalysisTable
        S3_BUCKET: !Ref ResumeBucket

Resources:
  # S3 Bucket for Resume Storage
  ResumeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub resume-analyzer-${AWS::AccountId}-${Environment}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldResumes
            Status: Enabled
            ExpirationInDays: 90

  # DynamoDB Table
  ResumeAnalysisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ResumeAnalysisResults-${Environment}
      AttributeDefinitions:
        - AttributeName: analysis_id
          AttributeType: S
      KeySchema:
        - AttributeName: analysis_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ResumeAnalyzerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ResumeBucket.Arn
                  - !Sub '${ResumeBucket.Arn}/*'
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: !GetAtt ResumeAnalysisTable.Arn
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: '*'

  # Resume Parser Lambda
  ResumeParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub resume-parser-${Environment}
      CodeUri: lambda/resume_parser/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - !Ref PyMuPDFLayer

  # Score Calculator Lambda
  ScoreCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub score-calculator-${Environment}
      CodeUri: lambda/score_calculator/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn

  # API Handler Lambda
  ApiHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub api-handler-${Environment}
      CodeUri: lambda/api_handler/
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          PARSER_FUNCTION: !Sub resume-parser-${Environment}
          SCORER_FUNCTION: !Sub score-calculator-${Environment}
      Events:
        ApiEvents:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

  # Lambda Layer for PyMuPDF
  PyMuPDFLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pymupdf-layer
      Description: PyMuPDF library for PDF parsing
      ContentUri: layers/pymupdf/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub ${AWS::StackName}-ApiEndpoint

  ResumeBucketName:
    Description: S3 bucket for resume uploads
    Value: !Ref ResumeBucket
    Export:
      Name: !Sub ${AWS::StackName}-BucketName

  DynamoDBTableName:
    Description: DynamoDB table for analysis results
    Value: !Ref ResumeAnalysisTable
    Export:
      Name: !Sub ${AWS::StackName}-TableName

  ResumeParserFunctionArn:
    Description: Resume Parser Lambda ARN
    Value: !GetAtt ResumeParserFunction.Arn

  ScoreCalculatorFunctionArn:
    Description: Score Calculator Lambda ARN
    Value: !GetAtt ScoreCalculatorFunction.Arn

  ApiHandlerFunctionArn:
    Description: API Handler Lambda ARN
    Value: !GetAtt ApiHandlerFunction.Arn
